#! /bin/bash

set -e

# TODO: Install homebrew
# TODO: Install MacVim/vim with lua support
# TODO: Install Ctags
# TODO: Install tmux
# TODO: Install reattach-to-user-namespace

# Set up submodules
git submodule init
git submodule update

# Checks for files that will be changed in ~
changed_files=(.tmux.conf .vimrc .gvimrc .ctags)

changed_file_exists=false

for file in "${changed_files[@]}"; do
  if [ -e "$HOME/$file" ]; then
    echo "$file exists!"
    changed_file_exists=true
  fi
done

if [ "$changed_file_exists" = true ]; then
  echo "Are you sure you want to overwrite these files? (y/n)"
  read resp
  if [ "$resp" != y ]; then
    exit 0
  fi
fi

# create symlinks
ln -sf "$(pwd)/tmux/tmux.conf" "$HOME/.tmux.conf"
ln -sf "$(pwd)/vim/vimrc" "$HOME/.vimrc"
ln -sf "$(pwd)/vim/gvimrc" "$HOME/.gvimrc"
ln -sf "$(pwd)/ctags/ctags" "$HOME/.ctags"

# install Vundle plugins
vim +PluginInstall +qall


# TODO: Replace YouCompleteMe with neocomplete
# Compile YouCompleteMe
# cd "$HOME/.vim/bundle/YouCompleteMe"
# ./install.sh --clang-completer
