set guifont=Menlo\ Regular:h12
set linespace=2
set antialias

" Don't beep
set visualbell

set guioptions-=T   " No toolbar
set guioptions-=r   " No scrollbars

if has("gui_macvim")
  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert
end


" hybrid number mode (vim 7.4+ only)
" Only enable in gvim since updating the screen
" is slow in the terminal
set relativenumber
set number
