set encoding=utf-8

" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'nanotech/jellybeans.vim'

call vundle#end()
filetype plugin indent on

colorscheme jellybeans
